// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_x6j3T12gbQ4xq0YxcYlye0MblT4YrBU',
    appId: '1:451637595298:ios:9be21feaf3a4be26b49bfb',
    messagingSenderId: '451637595298',
    projectId: 'safenow-c7fc7',
    storageBucket: 'safenow-c7fc7.firebasestorage.app',
    iosBundleId: 'com.example.safenow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_x6j3T12gbQ4xq0YxcYlye0MblT4YrBU',
    appId: '1:451637595298:ios:9be21feaf3a4be26b49bfb',
    messagingSenderId: '451637595298',
    projectId: 'safenow-c7fc7',
    storageBucket: 'safenow-c7fc7.firebasestorage.app',
    iosBundleId: 'com.example.safenow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgl4mcKomLa8FL5nS3qcyRj0neBTLNNHU',
    appId: '1:451637595298:web:6f5b332de0ed9a55b49bfb',
    messagingSenderId: '451637595298',
    projectId: 'safenow-c7fc7',
    authDomain: 'safenow-c7fc7.firebaseapp.com',
    storageBucket: 'safenow-c7fc7.firebasestorage.app',
    measurementId: 'G-H4F9028PVF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgl4mcKomLa8FL5nS3qcyRj0neBTLNNHU',
    appId: '1:451637595298:web:6f5b332de0ed9a55b49bfb',
    messagingSenderId: '451637595298',
    projectId: 'safenow-c7fc7',
    authDomain: 'safenow-c7fc7.firebaseapp.com',
    storageBucket: 'safenow-c7fc7.firebasestorage.app',
    measurementId: 'G-H4F9028PVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVcqzMIOqSKsam1XwmAQEzeFdS5Vgkac',
    appId: '1:451637595298:android:51a8867f53f4287bb49bfb',
    messagingSenderId: '451637595298',
    projectId: 'safenow-c7fc7',
    storageBucket: 'safenow-c7fc7.firebasestorage.app',
  );

}